# release.toml
allow-branch = ["master"]
tag-prefix = "v"                # tags like v0.2.1
tag-name = "{{prefix}}{{version}}"
sign-commit = false
sign-tag = false
push = true                     # push commits & tag
publish = false                 # don't publish to crates.io

# Optional: control the commit message for the version bump commit
pre-release-commit-message = "chore(release): {{version}}"
