name: Release (Linux only)

on:
  push:
    tags:
      - 'v*.*.*'   # v0.2.1, v1.0.0, etc.

permissions:
  contents: write   # required to create releases & upload assets

env:
  BIN_NAME: autovps

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]  # add aarch64-unknown-linux-gnu if you want it too
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: linux-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (${{ matrix.target }})
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package artifact
        run: |
          mkdir -p dist
          TGT=${{ matrix.target }}
          OUT=${BIN_NAME}-${TGT}
          # copy binary
          cp target/$TGT/release/${BIN_NAME} dist/$OUT
          # make a tar.gz too (nice for curl installs)
          tar -C dist -czf dist/${OUT}.tar.gz $OUT
          # checksums
          (cd dist && sha256sum $OUT > ${OUT}.sha256)
          (cd dist && sha256sum ${OUT}.tar.gz > ${OUT}.tar.gz.sha256)

      - uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifacts
        run: |
          mkdir -p upload
          find dist -type f -maxdepth 2 -exec mv {} upload/ \;
          ls -lah upload

      - name: Create/Update GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
