name: Build & Publish Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v1.2.3)"
        required: false

permissions:
  contents: write

env:
  BIN_NAME: autovps  # your binary name

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build (release)
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        shell: bash
        run: |
          set -euo pipefail
          OUTDIR="dist"
          mkdir -p "$OUTDIR"

          TAG="${{ github.ref_name || inputs.tag }}"
          ARCHIVE="${BIN_NAME}-${TAG}-${{ matrix.target }}"
          BIN="target/${{ matrix.target }}/release/${BIN_NAME}${{ matrix.ext }}"

          if [[ ! -f "$BIN" ]]; then
            echo "Expected binary not found: $BIN"
            exit 1
          fi

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a "${OUTDIR}/${ARCHIVE}.zip" "$BIN" >/dev/null
          else
